In [1]:
import numpy as np

In [2]:
a = np.arange(0,25).reshape(5,5)
a

array([[ 0,  1,  2,  3,  4],
       [ 5,  6,  7,  8,  9],
       [10, 11, 12, 13, 14],
       [15, 16, 17, 18, 19],
       [20, 21, 22, 23, 24]])

In [3]:
splitArr = np.hsplit(a, a.shape[1])
splitArr

[array([[ 0],
        [ 5],
        [10],
        [15],
        [20]]),
 array([[ 1],
        [ 6],
        [11],
        [16],
        [21]]),
 array([[ 2],
        [ 7],
        [12],
        [17],
        [22]]),
 array([[ 3],
        [ 8],
        [13],
        [18],
        [23]]),
 array([[ 4],
        [ 9],
        [14],
        [19],
        [24]])]

In [6]:
add5 = [i + 5 for i in splitArr]
add5

[array([[ 5],
        [10],
        [15],
        [20],
        [25]]),
 array([[ 6],
        [11],
        [16],
        [21],
        [26]]),
 array([[ 7],
        [12],
        [17],
        [22],
        [27]]),
 array([[ 8],
        [13],
        [18],
        [23],
        [28]]),
 array([[ 9],
        [14],
        [19],
        [24],
        [29]])]