In [1]:
import numpy as np

In [2]:
np.zeros(10)

array([0., 0., 0., 0., 0., 0., 0., 0., 0., 0.])

In [3]:
np.ones(10)

array([1., 1., 1., 1., 1., 1., 1., 1., 1., 1.])

In [4]:
np.ones(5)*5

array([5., 5., 5., 5., 5.])

In [15]:
a = np.arange(10,50).reshape(10,4)
a

array([[10, 11, 12, 13],
       [14, 15, 16, 17],
       [18, 19, 20, 21],
       [22, 23, 24, 25],
       [26, 27, 28, 29],
       [30, 31, 32, 33],
       [34, 35, 36, 37],
       [38, 39, 40, 41],
       [42, 43, 44, 45],
       [46, 47, 48, 49]])

In [19]:
a.ndim
a.shape
# a.size

(10, 4)

In [23]:
b = np.ones(4)
c = np.zeros(4)

In [25]:
# np.concatenate(b,c)

In [6]:
np.arange(0,9).reshape(3,3)

array([[0, 1, 2],
       [3, 4, 5],
       [6, 7, 8]])

In [7]:
np.eye(3)

array([[1., 0., 0.],
       [0., 1., 0.],
       [0., 0., 1.]])

In [29]:
np.random.rand(1)

array([0.1897025])

In [30]:
np.random.randn(25).reshape(5,5)

array([[-1.35741357, -2.88192004, -0.1149629 ,  0.69601981,  1.25389047],
       [ 1.61416638,  1.19944814, -1.09199411, -1.2185195 , -1.27992072],
       [ 0.80315865,  0.97700963,  0.18758445, -1.22766299, -2.49834572],
       [-0.23485933, -1.79051058,  0.88797758,  0.99221779, -0.09597612],
       [ 1.58234921,  2.67300712,  0.94674676, -0.14119767,  0.72014895]])

In [33]:
np.linspace(0,1,20)

array([0.        , 0.05263158, 0.10526316, 0.15789474, 0.21052632,
       0.26315789, 0.31578947, 0.36842105, 0.42105263, 0.47368421,
       0.52631579, 0.57894737, 0.63157895, 0.68421053, 0.73684211,
       0.78947368, 0.84210526, 0.89473684, 0.94736842, 1.        ])

In [34]:
a.sum()

1180

In [36]:
a = np.arange(1,26).reshape(5,5)
a

array([[ 1,  2,  3,  4,  5],
       [ 6,  7,  8,  9, 10],
       [11, 12, 13, 14, 15],
       [16, 17, 18, 19, 20],
       [21, 22, 23, 24, 25]])

In [38]:
a.sum(axis=0)

array([55, 60, 65, 70, 75])

In [39]:
a.sum(axis=1)

array([ 15,  40,  65,  90, 115])

In [40]:
a + 5

array([[ 6,  7,  8,  9, 10],
       [11, 12, 13, 14, 15],
       [16, 17, 18, 19, 20],
       [21, 22, 23, 24, 25],
       [26, 27, 28, 29, 30]])

In [47]:
x = np.random.randint(100,size = 10)

In [48]:
x

array([43, 72,  7, 83, 88, 17, 14, 21, 89, 20])

In [49]:
ind = [2,5,6]
x[ind]

array([ 7, 17, 14])

In [57]:
x.argmin()

2

In [60]:
od = np.array(1)
od

array(1)

In [62]:
td = np.arange(10,20).reshape(2,5)
td

array([[10, 11, 12, 13, 14],
       [15, 16, 17, 18, 19]])

In [66]:
dd = np.arange(0,27).reshape(3,3,3)
dd

array([[[ 0,  1,  2],
        [ 3,  4,  5],
        [ 6,  7,  8]],

       [[ 9, 10, 11],
        [12, 13, 14],
        [15, 16, 17]],

       [[18, 19, 20],
        [21, 22, 23],
        [24, 25, 26]]])

In [69]:
maths = np.random.randint(0,100,20)
maths

array([23, 28, 56,  9, 41, 93, 17, 65, 30, 43, 43, 56, 17, 75, 56, 25, 94,
        9, 96, 39])

In [72]:
np.sort(maths)

array([ 9,  9, 17, 17, 23, 25, 28, 30, 39, 41, 43, 43, 56, 56, 56, 65, 75,
       93, 94, 96])

In [74]:
np.sort(maths)[::-1]

array([96, 94, 93, 75, 65, 56, 56, 56, 43, 43, 41, 39, 30, 28, 25, 23, 17,
       17,  9,  9])

In [77]:
marks = maths.copy()
marks

array([ 9,  9, 17, 17, 23, 25, 28, 30, 39, 41, 43, 43, 56, 56, 56, 65, 75,
       93, 94, 96])

In [80]:
np.arange(0,25).reshape(5,5).ravel()

array([ 0,  1,  2,  3,  4,  5,  6,  7,  8,  9, 10, 11, 12, 13, 14, 15, 16,
       17, 18, 19, 20, 21, 22, 23, 24])

In [86]:
marks = marks.reshape(5,4)
marks

array([[ 9,  9, 17, 17],
       [23, 25, 28, 30],
       [39, 41, 43, 43],
       [56, 56, 56, 65],
       [75, 93, 94, 96]])

In [89]:
marks2 = [45, 34, 57, 76]
np.vstack((marks,marks2))

array([[ 9,  9, 17, 17],
       [23, 25, 28, 30],
       [39, 41, 43, 43],
       [56, 56, 56, 65],
       [75, 93, 94, 96],
       [45, 34, 57, 76]])

In [95]:
np.hsplit(marks,2)

[array([[ 9,  9],
        [23, 25],
        [39, 41],
        [56, 56],
        [75, 93]]),
 array([[17, 17],
        [28, 30],
        [43, 43],
        [56, 65],
        [94, 96]])]

In [106]:
np.vsplit(marks,(2,3))

[array([[ 9,  9, 17, 17],
        [23, 25, 28, 30]]),
 array([[39, 41, 43, 43]]),
 array([[56, 56, 56, 65],
        [75, 93, 94, 96]])]

In [113]:
np.amin(marks, axis=0)

array([ 9,  9, 17, 17])

In [111]:
np.amax(marks, axis=1)

array([17, 30, 43, 65, 96])

In [115]:
np.var(marks, axis=1)

array([16.    ,  7.25  ,  2.75  , 15.1875, 71.25  ])

In [116]:
np.std(marks, axis=1)

array([4.        , 2.6925824 , 1.6583124 , 3.89711432, 8.44097151])

In [121]:
def mat(s,e,st):
    return np.linspace(s,e,st).reshape(5,5)
mat(0,20,25)

array([[ 0.        ,  0.83333333,  1.66666667,  2.5       ,  3.33333333],
       [ 4.16666667,  5.        ,  5.83333333,  6.66666667,  7.5       ],
       [ 8.33333333,  9.16666667, 10.        , 10.83333333, 11.66666667],
       [12.5       , 13.33333333, 14.16666667, 15.        , 15.83333333],
       [16.66666667, 17.5       , 18.33333333, 19.16666667, 20.        ]])

In [122]:
np.nonzero(marks)

(array([0, 0, 0, 0, 1, 1, 1, 1, 2, 2, 2, 2, 3, 3, 3, 3, 4, 4, 4, 4]),
 array([0, 1, 2, 3, 0, 1, 2, 3, 0, 1, 2, 3, 0, 1, 2, 3, 0, 1, 2, 3]))

In [123]:
np.where(marks!=0)

(array([0, 0, 0, 0, 1, 1, 1, 1, 2, 2, 2, 2, 3, 3, 3, 3, 4, 4, 4, 4]),
 array([0, 1, 2, 3, 0, 1, 2, 3, 0, 1, 2, 3, 0, 1, 2, 3, 0, 1, 2, 3]))

In [156]:
m = np.ones((10,10))
n = np.ones((10,10))
m

array([[1., 1., 1., 1., 1., 1., 1., 1., 1., 1.],
       [1., 1., 1., 1., 1., 1., 1., 1., 1., 1.],
       [1., 1., 1., 1., 1., 1., 1., 1., 1., 1.],
       [1., 1., 1., 1., 1., 1., 1., 1., 1., 1.],
       [1., 1., 1., 1., 1., 1., 1., 1., 1., 1.],
       [1., 1., 1., 1., 1., 1., 1., 1., 1., 1.],
       [1., 1., 1., 1., 1., 1., 1., 1., 1., 1.],
       [1., 1., 1., 1., 1., 1., 1., 1., 1., 1.],
       [1., 1., 1., 1., 1., 1., 1., 1., 1., 1.],
       [1., 1., 1., 1., 1., 1., 1., 1., 1., 1.]])

In [157]:
m[1:-1, 1:-1] = 0

In [158]:
m

array([[1., 1., 1., 1., 1., 1., 1., 1., 1., 1.],
       [1., 0., 0., 0., 0., 0., 0., 0., 0., 1.],
       [1., 0., 0., 0., 0., 0., 0., 0., 0., 1.],
       [1., 0., 0., 0., 0., 0., 0., 0., 0., 1.],
       [1., 0., 0., 0., 0., 0., 0., 0., 0., 1.],
       [1., 0., 0., 0., 0., 0., 0., 0., 0., 1.],
       [1., 0., 0., 0., 0., 0., 0., 0., 0., 1.],
       [1., 0., 0., 0., 0., 0., 0., 0., 0., 1.],
       [1., 0., 0., 0., 0., 0., 0., 0., 0., 1.],
       [1., 1., 1., 1., 1., 1., 1., 1., 1., 1.]])

In [159]:
n[0,:] = 0
n[-1,:] = 0
n[:,0] = 0
n[:,-1] = 0

In [160]:
n

array([[0., 0., 0., 0., 0., 0., 0., 0., 0., 0.],
       [0., 1., 1., 1., 1., 1., 1., 1., 1., 0.],
       [0., 1., 1., 1., 1., 1., 1., 1., 1., 0.],
       [0., 1., 1., 1., 1., 1., 1., 1., 1., 0.],
       [0., 1., 1., 1., 1., 1., 1., 1., 1., 0.],
       [0., 1., 1., 1., 1., 1., 1., 1., 1., 0.],
       [0., 1., 1., 1., 1., 1., 1., 1., 1., 0.],
       [0., 1., 1., 1., 1., 1., 1., 1., 1., 0.],
       [0., 1., 1., 1., 1., 1., 1., 1., 1., 0.],
       [0., 0., 0., 0., 0., 0., 0., 0., 0., 0.]])

In [162]:
a = np.ones((8,8))
a[::2,::2] = 0
a[1::2,1::2] = 0
print(a)

[[0. 1. 0. 1. 0. 1. 0. 1.]
 [1. 0. 1. 0. 1. 0. 1. 0.]
 [0. 1. 0. 1. 0. 1. 0. 1.]
 [1. 0. 1. 0. 1. 0. 1. 0.]
 [0. 1. 0. 1. 0. 1. 0. 1.]
 [1. 0. 1. 0. 1. 0. 1. 0.]
 [0. 1. 0. 1. 0. 1. 0. 1.]
 [1. 0. 1. 0. 1. 0. 1. 0.]]


In [179]:
b = np.ones((8, 8))
b[::2, ::2] = np.nan
b[1::2, 1::2] = np.nan
print(b)

[[nan  1. nan  1. nan  1. nan  1.]
 [ 1. nan  1. nan  1. nan  1. nan]
 [nan  1. nan  1. nan  1. nan  1.]
 [ 1. nan  1. nan  1. nan  1. nan]
 [nan  1. nan  1. nan  1. nan  1.]
 [ 1. nan  1. nan  1. nan  1. nan]
 [nan  1. nan  1. nan  1. nan  1.]
 [ 1. nan  1. nan  1. nan  1. nan]]


In [180]:
nan_column = np.full((8, 1), np.nan)
b = np.hstack((b, nan_column))
b

array([[nan,  1., nan,  1., nan,  1., nan,  1., nan],
       [ 1., nan,  1., nan,  1., nan,  1., nan, nan],
       [nan,  1., nan,  1., nan,  1., nan,  1., nan],
       [ 1., nan,  1., nan,  1., nan,  1., nan, nan],
       [nan,  1., nan,  1., nan,  1., nan,  1., nan],
       [ 1., nan,  1., nan,  1., nan,  1., nan, nan],
       [nan,  1., nan,  1., nan,  1., nan,  1., nan],
       [ 1., nan,  1., nan,  1., nan,  1., nan, nan]])

In [181]:
# Convert NaNs to 1s
b[np.isnan(b)] = 0

print(b)

[[0. 1. 0. 1. 0. 1. 0. 1. 0.]
 [1. 0. 1. 0. 1. 0. 1. 0. 0.]
 [0. 1. 0. 1. 0. 1. 0. 1. 0.]
 [1. 0. 1. 0. 1. 0. 1. 0. 0.]
 [0. 1. 0. 1. 0. 1. 0. 1. 0.]
 [1. 0. 1. 0. 1. 0. 1. 0. 0.]
 [0. 1. 0. 1. 0. 1. 0. 1. 0.]
 [1. 0. 1. 0. 1. 0. 1. 0. 0.]]
